name: repair_holdings_flipbook
description: A Flutter web app showcasing Repair Holdings projects.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  turn_page_transition: ^0.4.0
  just_audio: ^0.10.4
  audioplayers: ^6.5.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image5.png
    - assets/images/image6.png
    - assets/images/image7.png
    - assets/images/image8.png
    - assets/images/image9.png
    - assets/images/image10.png
    - assets/images/image11.jpg
    - assets/sounds/
